version: "3.9"

services:
  
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d


