version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - backend

